name: gb-dicom2bids
channels:
  - conda-forge
dependencies:
  - python=3.11.16
  - pip
  - dcm2niix=1.0.20260416
  - dcmtk=3.7.0
  - gdcm=3.2.4
  - deno=2.9.0
  - matplotlib=3.11.1
  - nibabel=5.4.2
  - numpy=2.4.6
  - pydicom=3.0.2
  - psutil=7.2.2
  - pyyaml=6.0.3
  - simpleitk=2.5.6
  - pytest=8.4.2
  - pytest-cov=6.3.0
  - ruff=0.16.5
  - python-build=1.6.0
  - pip:
      - -e .
